### ISSUE TITLE
Can't run on linux

### ISSUE THREAD

**Issue by crondaemon** [enkomio/Mandolin0#1]
Having a look at the repo, it is not possible to run it in a linux-only environment.

In the git tree, there is no exe, nor in the distribution archive. I guess that it should be compiled under windows and then run on linux with mono. That makes impossible to run the software in a linux-only environment. Is there a way to obtain the compiled code or to compile it under linux?

**Comment by enkomio** [comment]
I have compiled it on windows and then testes on MAC OS. A compiled version of Mandolin0 can be downloaded from: https://github.com/enkomio/Mandolin0/releases/tag/v1.2.2

Unfortunately there are still some minor problems in running Mandolin0 on linux (see: http://stackoverflow.com/questions/28136346/how-to-catch-ctrlc-event-on-multithreads-net-program-in-a-portable-way), this mean that not all features that are available on windows are also available on linux (like session saving).

I hope to fix this problem in a future release.

I'm going to include a build script in the source tree in order to facilitate the build through the command line.
